spring:
  datasource:

    druid:
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/Test
      driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    database: 0
    port: 6379
  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
    virtual-host: /
    port: 5672

