spring:
  datasource:
    druid:
      one:
        username: root
        password: 123456
        url: jdbc:mysql://127.0.0.1:3306/Test?useSSL=false
        driver-class-name: com.mysql.jdbc.Driver
      two:
        username: root
        password: 123456
        url: jdbc:mysql://127.0.0.1:3306/Test?useSSL=false
        driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    database: 0
    port: 6379
  rabbitmq:
    addresses: localhost
    username: admin
    password: admin
    virtual-host: /
    port: 5672
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 10
  main:
    allow-bean-definition-overriding: true
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-critical-timeout: 30s
  application:
    name: unstoppable

